### ISSUE TITLE
Cache IP address location data

### ISSUE THREAD

**Issue by scottbarnesg** [scottbarnesg/WeatherByLocation#8]
Currently, we make a request to the external geolocation API to get the location of the server.

Instead, we should save this data locally, and only fetch location data if the IP address changes.

**Comment by adrienzag** [comment]
Hello,

I have taken a look at the repo and from what I can tell here it seems you are asking to adjust the ServerLocator.java so that before  we run the first line (line 55) of the function geolocateIpAddress(String ipAddress) we refer to our in memory db / cache  (be it Redis or Hazelcast etc) and if the key (in this case IP address) is found we unpack the value/blob attributed to it (and use that blob information to populate "locationResult" ) otherwise we create a new entry for it in the cache .

If this is accurate please let me know as I would like to take a crack at this issue.

Thanks

**Comment by scottbarnesg** [comment]
Hi @adrien2-public! Would love your help on this issue.

You are correct about the general approach, but instead of using an in-memory db or cache, the plugin should just write the result to a file. The plugin needs to just run without external dependencies like redis.

I'd propose the following approach:

- Get the current IP address of the server (as is done currently)
- Check the file to see if the IP address of the server is stored there. If so, read it and use those location values (latitude, longitude, city, region, country) to pull weather data.
- If not, call `geolocateIPAddress()` (as is done currently). Write this data to the file so that it is associated with the IP address. (This data will then be used the next time the server is started).

To keep the implementation simple, we can just store 1 IP address and its geolocation data, and if the server's IP address changes, we'll overwrite it.

Currently, we read and write data to `config.yml` using the Bukkit `JavaPlugin.getConfig()` functions.

Let me know if you have any questions!

**Comment by adrienzag** [comment]
Ok I see,

I have forked the repo and will try to make a pull request in a few days once i get the chance to retest my changes

It seems that it is considered bad practice to have multiple extensions of JavaPlugin across several classes, I also saw that WeatherBylocation is likely to  be the preferred entry point for many things so i had opted for making a small change to
the WeatherBylocation class by:

- under the runStartupTasks() - line 103, the instantiation of Serverlocator now takes a WeatherByLocation variable called plugin, to give us access to the JavaPlugin within the Serverlocator class (just like SetLocationCommand )

Within the Serverlocator class the following changes happen:
- Serverlocator constructor now takes WeatherByLocation variable called plugin
- locate() function creates config object (of FileConfiguration type) , and checks for existance of "ipaddress" and checks to see if the fetched ipAdress is identical
  if that is the case, fucntion call to locationDataFromConfig(config) is made and a locationData object is returned. Otherwise
  the geolocateIpAddress(ipAddress,config) is called, important to note that config variable is added as parameter for both previous functions to give access to current config.yml value pairs
- locationDataFromConfig(config) gets data from the config file
- geolocateIpAddress(ipAddress,config) does the same thing as before but now also saves new data to config file at the end of function

**Comment by scottbarnesg** [comment]
That approach sounds about right to me. Happy to do a code review when you have something working
